language: node_js
node_js:
  - "6"
  - "7"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  - CXX=g++-4.8
cache:
  directories:
    - node_modules
install:
  - export CXX="g++-4.8"
after_script: "npm run test"
